services:
  redis:
    image: redis:6.2.3-alpine
    ports:
      - 6379:6379
    restart: unless-stopped
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    depends_on:
     - redis
  
  go-hipache:
    build:
      context: ./go-hipache
    ports:
      - 9000:9000
      - 2525:2525
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT_RANGE=2525,9000-9010
    healthcheck:
      test: "curl http://localhost:2525/!metrics"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
     - redis
     - mb
     - mb-debug

  ####################################################
  # Mountebank Pool Watcher - Watches docker events and updates redis when 
  # mb instances are dropped or added
  watcher:
    build:
      context: ./watcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  
  ###################################
  # PERFORMANCE MOUNTEBANK INSTANCES
  ###################################
  mb:
    image: bbyars/mountebank
    # build:
      # context: ./mountebank-pool
    command: "--no-mock --no-recordRequests --loglevel silent --nologfile --allowInjection" # --impostersRepository=/app/config/impostersRepo.js"
    healthcheck: 
      test: "wget --no-verbose --tries=1 --spider http://localhost:2525 || exit 1"
      interval: 5s
      timeout: 10s
      retries: 6
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    deploy:
      replicas: 10
    depends_on:
      - watcher
  
  #############################
  # DEBUG MOUNTEBANK INSTANCES
  #############################
  mb-debug:
    image: bbyars/mountebank
    # build:
      # context: ./mountebank-pool
    command: "--recordRequests --loglevel debug --debug --allowInjection --logfile /mb-debug.log" # --impostersRepository=/app/config/impostersRepo.js"
    healthcheck: 
      test: "wget --no-verbose --tries=1 --spider http://localhost:2525 || exit 1"
      interval: 5s
      timeout: 10s
      retries: 6
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    deploy:
      replicas: 1
    depends_on:
      - watcher

