name: Execute Benchmarks

on:
  workflow_dispatch:

env:
  HOME: /home/runner/work/dynamic-load-balancer/dynamic-load-balancer

jobs:
  test1:
    name: Test 1 - Regular NGINX
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Status Check
        run: |
          pwd
          ls
          cat /proc/cpuinfo
          cat /proc/meminfo

      - name: Start up stack
        # run: docker-compose -f${{ env.HOME }}/docker-compose.yml -f${{ env.HOME }}/test/docker-compose-baseline.yml up -d
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "./test/docker-compose-baseline.yml"
          compose-flags: "-p dynamic-load-balancer"
          up-flags: "--wait -d"

      - name: Wait for mb configuration to deploy
        run: docker logs -f dynamic-load-balancer-mb-conf-1 

      - name: Confirm sim is reachable
        run: curl -v http://localhost:9000/customers/1230
      
      - name: Run K6 Benchmark for Test 1 @ 100 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 100 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 200 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 200 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 300 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 300 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 400 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 400 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 500 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 500 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 600 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 600 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 700 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 700 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 800 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 800 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 900 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 900 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 1000 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 1000 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 1 @ 1100 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 1100 --duration 1m /script.js

      # - name: Print Telegraf metrics for Test 1
      #   run: |
      #     ls${{ env.HOME }}/output/*
      #     cat${{ env.HOME }}/output/metrics.out
      #     echo "" >${{ env.HOME }}/output/metrics.out

  test2:
    name: Test 2 - Dynamic Load Balancer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Status Check
        run: |
          pwd
          ls
          cat /proc/cpuinfo
          cat /proc/meminfo
          
      - name: Start up stack
        # run: docker-compose -f${{ env.HOME }}/docker-compose.yml up --build -d
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          # compose-file: "./docker-compose.yml"
          compose-flags: "-p dynamic-load-balancer -f ./docker-compose.yml -f ./test/docker-compose-test.yml"
          up-flags: "--wait --build -d"

      - name: Wait for mb configuration to deploy
        run: docker logs -f dynamic-load-balancer-mb-conf-1 

      - name: Confirm sim is reachable
        run: curl -v http://localhost:9000/customers/1230
      
      - name: Run K6 Benchmark for Test 2 @ 100 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 100 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 200 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 200 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 300 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 300 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 400 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 400 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 500 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 500 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 600 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 600 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 700 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 700 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 800 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 800 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 900 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 900 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 1000 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 1000 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 1100 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 1100 --duration 1m /script.js

  test3:
    name: Test 3 - Go-Lang Dynamic Load Balancer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Status Check
        run: |
          pwd
          ls
          cat /proc/cpuinfo
          cat /proc/meminfo
          
      - name: Start up stack
        # run: docker-compose -f${{ env.HOME }}/docker-compose.yml up --build -d
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "./docker-compose.go-hipache.yml"
          compose-flags: "-p dynamic-load-balancer -f ./docker-compose.go-hipache.yml -f ./test/docker-compose-test2.yml"
          up-flags: "--wait --build -d"

      - name: Wait for mb configuration to deploy
        run: docker logs -f dynamic-load-balancer-mb-conf-1 

      - name: Confirm sim is reachable
        run: curl -v http://localhost:9000/customers/1230
      
      - name: Run K6 Benchmark for Test 2 @ 100 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 100 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 200 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 200 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 300 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 300 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 400 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 400 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 500 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 500 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 600 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 600 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 700 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 700 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 800 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 800 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 900 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 900 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 1000 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 1000 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 1100 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 1100 --duration 1m /script.js

  test4:
    name: Test 4 - NGINX Custom Module - Dynamic Load Balancer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Status Check
        run: |
          pwd
          ls
          cat /proc/cpuinfo
          cat /proc/meminfo
          
      - name: Start up stack
        # run: docker-compose -f${{ env.HOME }}/docker-compose.yml up --build -d
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "./docker-compose.nginx-custom.yml"
          compose-flags: "-p dynamic-load-balancer -f ./docker-compose.nginx-custom.yml -f ./test/docker-compose-test.yml"
          up-flags: "--wait --build -d"

      - name: Wait for mb configuration to deploy
        run: docker logs -f dynamic-load-balancer-mb-conf-1 

      - name: Confirm sim is reachable
        run: curl -v http://localhost:9000/customers/1230
      
      - name: Run K6 Benchmark for Test 2 @ 100 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 100 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 200 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 200 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 300 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 300 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 400 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 400 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 500 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 500 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 600 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 600 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 700 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 700 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 800 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 800 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 900 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 900 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 1000 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 1000 --duration 1m /script.js

      - name: Run K6 Benchmark for Test 2 @ 1100 vus
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6
          options: --name k6 --rm -v${{ env.HOME }}/test/script.js:/script.js --network host
          run: k6 run --vus 1100 --duration 1m /script.js





      